version: '3'
services: 
  app:
    image: nginx:1.13
    volumes:
      # Site
      - ./app/ui-flow/build:/usr/share/nginx/html/
      # Reverse proxy
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  # db: 
  #   image: postgres:12
  #   restart: always
  #   environment: 
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5433:5432
  server:
    build: ./server
    volumes:
      - ./server:/home/node/server
    # environment: 
    #   DB_HOST: 127.0.0.1
    #   DB_PORT: 5433
    ports:
      - 5000:5000
    # depends_on:  
    #   - db

volumes:
  data: